"""renombrar columna y modificar enum 

Revision ID: 0645b7071b6a
Revises: edf24944fc17
Create Date: 2021-11-25 14:57:02.595731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0645b7071b6a'
down_revision = 'edf24944fc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regimen_disciplinario', sa.Column(
        'id_estado_sumario', postgresql.UUID(), nullable=False))
    op.drop_constraint('regimen_disciplinario_estado_sumario_fkey',
                       'regimen_disciplinario', type_='foreignkey')
    op.create_foreign_key('regimen_disciplinario_id_estado_sumario_fkey',
                          'regimen_disciplinario', 'estados_sumarios', ['id_estado_sumario'], ['id'])
    op.drop_column('regimen_disciplinario', 'estado_sumario')
    op.alter_column('detalles_expedientes_laborales', 'tipo_personal', type_=sa.Enum(
        'FUNCIONARIO', 'PROFESOR', name='tipoPersonal'), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regimen_disciplinario', sa.Column(
        'estado_sumario', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('regimen_disciplinario_id_estado_sumario_fkey',
                       'regimen_disciplinario', type_='foreignkey')
    op.create_foreign_key('regimen_disciplinario_estado_sumario_fkey',
                          'regimen_disciplinario', 'estados_sumarios', ['estado_sumario'], ['id'])
    op.drop_column('regimen_disciplinario', 'id_estado_sumario')
    op.alter_column('detalles_expedientes_laborales', 'tipo_personal', type_=sa.Enum(
        'FUNCIONARIIO', 'PROFESOR', name='tipoPersonal'), nullable=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###
