"""renombrar columna fecha_presentación a fecha_presentacion

Revision ID: 131994d1e88b
Revises: 0645b7071b6a
Create Date: 2021-11-26 09:45:35.213593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131994d1e88b'
down_revision = '0645b7071b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('declaraciones_patrimoniales', sa.Column('fecha_presentacion', sa.Date(), nullable=False))
    op.drop_column('declaraciones_patrimoniales', 'fecha_presentación')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('declaraciones_patrimoniales', sa.Column('fecha_presentación', sa.Date(),  nullable=False))
    op.drop_column('declaraciones_patrimoniales', 'fecha_presentacion')
    # ### end Alembic commands ###
