"""cargar datos en tabla ies_nacionales

Revision ID: 27b07307ae73
Revises: 6cf89f8285ea
Create Date: 2021-10-21 09:07:13.733394

"""
from typing import List
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import session
from app.utils.cargar_datos import CsvtoList
from app.models.core.modelos_principales import IESNacional
from sqlalchemy.orm.session import Session
from sqlalchemy.sql.expression import delete
import platform

# revision identifiers, used by Alembic.
revision = '27b07307ae73'
down_revision = '6cf89f8285ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print(f'Insertando datos en tabla {IESNacional.__tablename__}')
    sesion = Session(bind=op.get_bind())
    try:
        file_path = '.\\app\\utils\\ies_nacionales.csv'
        if platform.system() == 'Linux':
            file_path = './/app//utils//ies_nacionales.csv'

        listado_ies = CsvtoList(filename=file_path)
        ies_nacionales: List[IESNacional] = []
        for ies in listado_ies.getList():
            ies_nacionales.append(
                IESNacional(
                    codigo= ies['codigo'],
                    institucion = ies['institucion']
                    ))
        sesion.add_all(ies_nacionales)
        sesion.commit()
        print("Datos insertados")
    except Exception as ex:
        print(ex)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())
    session.execute(
        delete(IESNacional)
    )
    session.commit()
    session.close()
    # ### end Alembic commands ###
