"""cambios en la definicion de los modelos

Revision ID: 323dec9a673b
Revises: da51b9dfff5f
Create Date: 2021-07-29 14:47:23.935645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '323dec9a673b'
down_revision = 'da51b9dfff5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cantones', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('cantones', sa.Column('actualizado_en', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('cantones', 'canton',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.add_column('categorias_contratos_profesores', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('categorias_contratos_profesores', sa.Column('actualizado_en', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('categorias_contratos_profesores', 'categoria_contrato',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('categorias_docentes_losep', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('categorias_docentes_losep', sa.Column('actualizado_en', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('cuentas_usuarios', sa.Column('estado', sa.Boolean(), nullable=True))
    op.add_column('cuentas_usuarios', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('cuentas_usuarios', sa.Column('actualizado_en', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('cuentas_usuarios', 'primer_nombre',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('cuentas_usuarios', 'segundo_nombre',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('cuentas_usuarios', 'primer_apellido',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('cuentas_usuarios', 'segundo_segundo',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('cuentas_usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cuentas_usuarios', 'clave_encriptada',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('discapacidades', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('discapacidades', sa.Column('actualizado_en', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('etnias', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('etnias', sa.Column('actualizado_en', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('etnias', 'etnia',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'etnias', ['etnia'])
    op.add_column('nacionalidades', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('nacionalidades', sa.Column('actualizado_en', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('nacionalidades', 'nacionalidad',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('nivel_educativo', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('nivel_educativo', sa.Column('actualizado_en', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('nivel_educativo', 'nivel',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('paises', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('paises', sa.Column('actualizado_en', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('paises', 'pais',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.add_column('provincias', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('provincias', sa.Column('actualizado_en', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('provincias', 'provincia',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.add_column('relaciones_ies', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('relaciones_ies', sa.Column('actualizado_en', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('relaciones_ies', 'relacion',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('roles', 'rol',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('roles', 'descripcion',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.add_column('tiempo_dedicacion_profesores', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tiempo_dedicacion_profesores', sa.Column('actualizado_en', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('tiempo_dedicacion_profesores', 'tiempo_dedicacion',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('tipo_funcionarios', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tipo_funcionarios', sa.Column('actualizado_en', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('tipo_funcionarios', 'tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('tipos_docente_loes', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tipos_docente_loes', sa.Column('actualizado_en', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('tipos_docente_loes', 'tipo_docente',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('tipos_documento', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tipos_documento', sa.Column('actualizado_en', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('tipos_documento', 'tipo_documento',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('tipos_relaciones_nombramientos', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tipos_relaciones_nombramientos', sa.Column('actualizado_en', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('tipos_relaciones_nombramientos', 'relacion_nombramiento',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('tokens_autorizaciones', 'tipo_token',
               existing_type=postgresql.ENUM('acceso', 'solicitud_cambio_calve', name='tipotoken'),
               nullable=False)
    op.alter_column('tokens_autorizaciones', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens_autorizaciones', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tokens_autorizaciones', 'tipo_token',
               existing_type=postgresql.ENUM('acceso', 'solicitud_cambio_calve', name='tipotoken'),
               nullable=True)
    op.alter_column('tipos_relaciones_nombramientos', 'relacion_nombramiento',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('tipos_relaciones_nombramientos', 'actualizado_en')
    op.drop_column('tipos_relaciones_nombramientos', 'registrado_en')
    op.alter_column('tipos_documento', 'tipo_documento',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('tipos_documento', 'actualizado_en')
    op.drop_column('tipos_documento', 'registrado_en')
    op.alter_column('tipos_docente_loes', 'tipo_docente',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('tipos_docente_loes', 'actualizado_en')
    op.drop_column('tipos_docente_loes', 'registrado_en')
    op.alter_column('tipo_funcionarios', 'tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('tipo_funcionarios', 'actualizado_en')
    op.drop_column('tipo_funcionarios', 'registrado_en')
    op.alter_column('tiempo_dedicacion_profesores', 'tiempo_dedicacion',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('tiempo_dedicacion_profesores', 'actualizado_en')
    op.drop_column('tiempo_dedicacion_profesores', 'registrado_en')
    op.alter_column('roles', 'descripcion',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('roles', 'rol',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('relaciones_ies', 'relacion',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('relaciones_ies', 'actualizado_en')
    op.drop_column('relaciones_ies', 'registrado_en')
    op.alter_column('provincias', 'provincia',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('provincias', 'actualizado_en')
    op.drop_column('provincias', 'registrado_en')
    op.alter_column('paises', 'pais',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('paises', 'actualizado_en')
    op.drop_column('paises', 'registrado_en')
    op.alter_column('nivel_educativo', 'nivel',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('nivel_educativo', 'actualizado_en')
    op.drop_column('nivel_educativo', 'registrado_en')
    op.alter_column('nacionalidades', 'nacionalidad',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('nacionalidades', 'actualizado_en')
    op.drop_column('nacionalidades', 'registrado_en')
    op.drop_constraint(None, 'etnias', type_='unique')
    op.alter_column('etnias', 'etnia',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('etnias', 'actualizado_en')
    op.drop_column('etnias', 'registrado_en')
    op.drop_column('discapacidades', 'actualizado_en')
    op.drop_column('discapacidades', 'registrado_en')
    op.alter_column('cuentas_usuarios', 'clave_encriptada',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cuentas_usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cuentas_usuarios', 'segundo_segundo',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('cuentas_usuarios', 'primer_apellido',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('cuentas_usuarios', 'segundo_nombre',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('cuentas_usuarios', 'primer_nombre',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('cuentas_usuarios', 'actualizado_en')
    op.drop_column('cuentas_usuarios', 'registrado_en')
    op.drop_column('cuentas_usuarios', 'estado')
    op.drop_column('categorias_docentes_losep', 'actualizado_en')
    op.drop_column('categorias_docentes_losep', 'registrado_en')
    op.alter_column('categorias_contratos_profesores', 'categoria_contrato',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('categorias_contratos_profesores', 'actualizado_en')
    op.drop_column('categorias_contratos_profesores', 'registrado_en')
    op.alter_column('cantones', 'canton',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('cantones', 'actualizado_en')
    op.drop_column('cantones', 'registrado_en')
    # ### end Alembic commands ###
