"""cambios en modelo direccion

Revision ID: 361677108e35
Revises: df93d61531bc
Create Date: 2021-09-15 10:16:38.462136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361677108e35'
down_revision = 'df93d61531bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datos_personales', sa.Column('lincencia_conduccion', sa.String(length=2), nullable=False))
    op.drop_column('datos_personales', 'lencencia_coduccion')
    op.add_column('direcciones_domiciliarias', sa.Column('parroquia', sa.String(length=40), nullable=False))
    op.add_column('direcciones_domiciliarias', sa.Column('referencia', sa.String(length=120), nullable=True))
    op.drop_column('direcciones_domiciliarias', 'id_parroquia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direcciones_domiciliarias', sa.Column('id_parroquia', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('direcciones_domiciliarias', 'referencia')
    op.drop_column('direcciones_domiciliarias', 'parroquia')
    op.add_column('datos_personales', sa.Column('lencencia_coduccion', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_column('datos_personales', 'lincencia_conduccion')
    # ### end Alembic commands ###
