"""Primera migración

Revision ID: 3aca6869685a
Revises: 
Create Date: 2021-07-27 09:24:18.177162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3aca6869685a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_contratos_profesores',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('categoria_contrato', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria_contrato')
    )
    op.create_index(op.f('ix_categorias_contratos_profesores_id'), 'categorias_contratos_profesores', ['id'], unique=False)
    op.create_table('categorias_docentes_losep',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('categoria_docente', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria_docente')
    )
    op.create_index(op.f('ix_categorias_docentes_losep_id'), 'categorias_docentes_losep', ['id'], unique=False)
    op.create_table('cuentas_usuarios',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=30), nullable=True),
    sa.Column('segundo_nombre', sa.String(length=30), nullable=True),
    sa.Column('primer_apellido', sa.String(length=30), nullable=True),
    sa.Column('segundo_segundo', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('clave_encriptada', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentas_usuarios_id'), 'cuentas_usuarios', ['id'], unique=False)
    op.create_table('discapacidades',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('discapacidad', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discapacidad')
    )
    op.create_index(op.f('ix_discapacidades_id'), 'discapacidades', ['id'], unique=False)
    op.create_table('etnias',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('etnia', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etnias_id'), 'etnias', ['id'], unique=False)
    op.create_table('nacionalidades',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('nacionalidad', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nacionalidad')
    )
    op.create_index(op.f('ix_nacionalidades_id'), 'nacionalidades', ['id'], unique=False)
    op.create_table('nivel_educativo',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nivel')
    )
    op.create_index(op.f('ix_nivel_educativo_id'), 'nivel_educativo', ['id'], unique=False)
    op.create_table('relaciones_ies',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('relacion', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relacion')
    )
    op.create_index(op.f('ix_relaciones_ies_id'), 'relaciones_ies', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('tiempo_dedicacion_profesores',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('tiempo_dedicacion', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tiempo_dedicacion')
    )
    op.create_index(op.f('ix_tiempo_dedicacion_profesores_id'), 'tiempo_dedicacion_profesores', ['id'], unique=False)
    op.create_table('tipo_funcionarios',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.create_index(op.f('ix_tipo_funcionarios_id'), 'tipo_funcionarios', ['id'], unique=False)
    op.create_table('tipos_docente_loes',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('tipo_docente', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_docente')
    )
    op.create_index(op.f('ix_tipos_docente_loes_id'), 'tipos_docente_loes', ['id'], unique=False)
    op.create_table('tipos_documento',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_documento')
    )
    op.create_index(op.f('ix_tipos_documento_id'), 'tipos_documento', ['id'], unique=False)
    op.create_table('tipos_relaciones_nombramientos',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('relacion_nombramiento', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relacion_nombramiento')
    )
    op.create_index(op.f('ix_tipos_relaciones_nombramientos_id'), 'tipos_relaciones_nombramientos', ['id'], unique=False)
    op.create_table('roles_usuarios',
    sa.Column('rol_id', postgresql.UUID(), nullable=True),
    sa.Column('right_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['right_id'], ['cuentas_usuarios.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_usuarios')
    op.drop_index(op.f('ix_tipos_relaciones_nombramientos_id'), table_name='tipos_relaciones_nombramientos')
    op.drop_table('tipos_relaciones_nombramientos')
    op.drop_index(op.f('ix_tipos_documento_id'), table_name='tipos_documento')
    op.drop_table('tipos_documento')
    op.drop_index(op.f('ix_tipos_docente_loes_id'), table_name='tipos_docente_loes')
    op.drop_table('tipos_docente_loes')
    op.drop_index(op.f('ix_tipo_funcionarios_id'), table_name='tipo_funcionarios')
    op.drop_table('tipo_funcionarios')
    op.drop_index(op.f('ix_tiempo_dedicacion_profesores_id'), table_name='tiempo_dedicacion_profesores')
    op.drop_table('tiempo_dedicacion_profesores')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_relaciones_ies_id'), table_name='relaciones_ies')
    op.drop_table('relaciones_ies')
    op.drop_index(op.f('ix_nivel_educativo_id'), table_name='nivel_educativo')
    op.drop_table('nivel_educativo')
    op.drop_index(op.f('ix_nacionalidades_id'), table_name='nacionalidades')
    op.drop_table('nacionalidades')
    op.drop_index(op.f('ix_etnias_id'), table_name='etnias')
    op.drop_table('etnias')
    op.drop_index(op.f('ix_discapacidades_id'), table_name='discapacidades')
    op.drop_table('discapacidades')
    op.drop_index(op.f('ix_cuentas_usuarios_id'), table_name='cuentas_usuarios')
    op.drop_table('cuentas_usuarios')
    op.drop_index(op.f('ix_categorias_docentes_losep_id'), table_name='categorias_docentes_losep')
    op.drop_table('categorias_docentes_losep')
    op.drop_index(op.f('ix_categorias_contratos_profesores_id'), table_name='categorias_contratos_profesores')
    op.drop_table('categorias_contratos_profesores')
    # ### end Alembic commands ###
