"""tabla tokens_autorizaciones

Revision ID: 424db458b394
Revises: 3aca6869685a
Create Date: 2021-07-27 11:41:16.471925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '424db458b394'
down_revision = '3aca6869685a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens_autorizaciones',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('tipo_token', sa.Enum('acceso', 'solicitud_cambio_calve', name='tipotoken'), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('usuario_id', postgresql.UUID(), nullable=True),
    sa.Column('generado_en', sa.DateTime(), nullable=True),
    sa.Column('usado_hasta', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['cuentas_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_autorizaciones_id'), 'tokens_autorizaciones', ['id'], unique=False)
    op.add_column('roles_usuarios', sa.Column('usuario_id', postgresql.UUID(), nullable=True))
    op.drop_constraint('roles_usuarios_right_id_fkey', 'roles_usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'roles_usuarios', 'cuentas_usuarios', ['usuario_id'], ['id'])
    op.drop_column('roles_usuarios', 'right_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles_usuarios', sa.Column('right_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'roles_usuarios', type_='foreignkey')
    op.create_foreign_key('roles_usuarios_right_id_fkey', 'roles_usuarios', 'cuentas_usuarios', ['right_id'], ['id'])
    op.drop_column('roles_usuarios', 'usuario_id')
    op.drop_index(op.f('ix_tokens_autorizaciones_id'), table_name='tokens_autorizaciones')
    op.drop_table('tokens_autorizaciones')
    # ### end Alembic commands ###
