"""cambios en modelos 03/08/2021

Revision ID: 471d53bfb20c
Revises: 323dec9a673b
Create Date: 2021-08-03 16:34:55.272178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471d53bfb20c'
down_revision = '323dec9a673b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipos_relaciones_nombramientos', sa.Column('escalafon_nombramiento', sa.String(length=50), nullable=False))
    op.drop_constraint('tipos_relaciones_nombramientos_relacion_nombramiento_key', 'tipos_relaciones_nombramientos', type_='unique')
    op.create_unique_constraint(None, 'tipos_relaciones_nombramientos', ['escalafon_nombramiento'])
    op.drop_column('tipos_relaciones_nombramientos', 'relacion_nombramiento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipos_relaciones_nombramientos', sa.Column('relacion_nombramiento', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tipos_relaciones_nombramientos', type_='unique')
    op.create_unique_constraint('tipos_relaciones_nombramientos_relacion_nombramiento_key', 'tipos_relaciones_nombramientos', ['relacion_nombramiento'])
    op.drop_column('tipos_relaciones_nombramientos', 'escalafon_nombramiento')
    # ### end Alembic commands ###
