"""cargar datos en tablas relacionadas con el campo de estudio

Revision ID: 4ddffce21037
Revises: e86feeb8c8f7
Create Date: 2021-10-20 15:37:50.356750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import session
from sqlalchemy.sql.expression import select
from app.models.core.modelos_principales import CampoEducativoAmplio, CampoEducativoEspecifico, CampoEducativoDetallado
import json
from sqlalchemy.orm.session import Session

# revision identifiers, used by Alembic.
revision = '4ddffce21037'
down_revision = 'e86feeb8c8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())
    try:
        file_path = '.\\app\\utils\\campo_educativo.json'
        with open(file_path, encoding='utf8') as f:
            campos_educativos = json.load(f)
            print("test",campos_educativos)
        '''for campo_educativo in campos_educativos:
            especificos = []
            campo = CampoEducativoAmplio()
            campo.codigo = campo_educativo['codigo']
            campo.descripcion = campo_educativo['descripcion']
            for especifico in campo_educativo['especificos']:
                detallados = []
                campo_especifico = CampoEducativoEspecifico()
                campo_especifico.codigo = especifico['codigo']
                campo_especifico.descripcion = especifico['descripcion']
                for detalle in especifico['detallados']:
                    campo_detallado = CampoEducativoDetallado()
                    campo_detallado.codigo = detalle['codigo']
                    campo_detallado.descripcion = detalle['descripcion']
                    detallados.append(campo_detallado)
                campo_especifico.campos_detallados = detallados
                especificos.append(campo_especifico)
            campo.campos_especificos = especificos
            session.add(especifico)
        session.commit()'''
    except  Exception as ex:
        print(ex)
    finally:
        session.close()
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
