"""tabla paises y carga de datos

Revision ID: 51e67ffe7260
Revises: 424db458b394
Create Date: 2021-07-28 10:37:36.591523

"""
from alembic import op
import sqlalchemy as sa
from app.utils.cargar_datos import CsvtoList

# revision identifiers, used by Alembic.
revision = '51e67ffe7260'
down_revision = '424db458b394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    paises = op.create_table('paises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=120), nullable=True),
    sa.Column('nacionalidad', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paises_id'), 'paises', ['id'], unique=False)

    print("Insertando datos ...")
    try:
        file_path = '.\\app\\utils\\listado_paises.csv'
        listado_paises = CsvtoList(filename=file_path)
        op.bulk_insert(paises, listado_paises.getList(),  multiinsert=False)  
        print("Datos insertados")
    except Exception as ex:

        print(f"{ex}")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paises_id'), table_name='paises')
    op.drop_table('paises')
    # ### end Alembic commands ###
