"""cambios en modelos dath

Revision ID: 58c1e914b39a
Revises: 9c87666b10bc
Create Date: 2021-11-17 14:02:24.862172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.models.dath.modelos import TipoLicenciaConduccion

# revision identifiers, used by Alembic.
revision = '58c1e914b39a'
down_revision = '9c87666b10bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_sumarios',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('estaso', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_sumarios_id'), 'estados_sumarios', ['id'], unique=False)
    op.create_table('modalidades_contractuales',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('modalidad', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modalidades_contractuales_id'), 'modalidades_contractuales', ['id'], unique=False)
    op.create_table('motivos_desvinculacion',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('motivo', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motivos_desvinculacion_id'), 'motivos_desvinculacion', ['id'], unique=False)
    op.create_table('regimenes_laborales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regimen', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sanciones',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('sancion', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanciones_id'), 'sanciones', ['id'], unique=False)
    op.create_table('tipos_contratos',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('contrato', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_contratos_id'), 'tipos_contratos', ['id'], unique=False)
    op.create_table('tipos_nombramientos',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('nombramiento', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_nombramientos_id'), 'tipos_nombramientos', ['id'], unique=False)
    op.create_table('contactos_emergencia_personal',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('id_persona', sa.String(length=10), nullable=False),
    sa.Column('apellidos', sa.String(length=80), nullable=False),
    sa.Column('nombres', sa.String(length=80), nullable=False),
    sa.Column('direccion', sa.String(length=120), nullable=False),
    sa.Column('telefono_domicilio', sa.String(length=10), nullable=True),
    sa.Column('telefono_movil', sa.String(length=13), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['datos_personales.identificacion'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contactos_emergencia_personal_id'), 'contactos_emergencia_personal', ['id'], unique=False)
    op.create_table('informacion_bancaria_personal',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('id_persona', sa.String(length=10), nullable=False),
    sa.Column('institucion_financiera', sa.String(length=120), nullable=False),
    sa.Column('tipo_cuenta', sa.Enum('AHORRO', 'CORRIENTE', name='tipoCuenta'), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['datos_personales.identificacion'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_informacion_bancaria_personal_id'), 'informacion_bancaria_personal', ['id'], unique=False)
    op.create_table('regimen_disciplinario',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('anio_sancion', sa.Integer(), nullable=False),
    sa.Column('mes_sancion', sa.Enum('ENERO', 'FEBREO', 'MARZO', 'ABRIL', 'MAYO', 'JUNIO', 'JULIO', 'AGOSTO', 'SEPTIEMBRE', 'OCTUBRE', 'NOVIEMBRE', 'DICIEMBFRE', name='mes'), nullable=True),
    sa.Column('id_persona', sa.String(length=10), nullable=False),
    sa.Column('id_regimen', sa.Integer(), nullable=False),
    sa.Column('id_modalidad', postgresql.UUID(), nullable=True),
    sa.Column('tipo_falta', sa.Enum('LEVES', 'GRAVES', name='tipoFalta'), nullable=False),
    sa.Column('id_sancion', postgresql.UUID(), nullable=True),
    sa.Column('aplica_sumario', sa.String(length=2), nullable=False),
    sa.Column('estado_sumario', postgresql.UUID(), nullable=False),
    sa.Column('numero_sentencia', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['estado_sumario'], ['estados_sumarios.id'], ),
    sa.ForeignKeyConstraint(['id_modalidad'], ['modalidades_contractuales.id'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['datos_personales.identificacion'], ),
    sa.ForeignKeyConstraint(['id_regimen'], ['regimenes_laborales.id'], ),
    sa.ForeignKeyConstraint(['id_sancion'], ['sanciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regimen_disciplinario_id'), 'regimen_disciplinario', ['id'], unique=False)
    op.create_table('sustitutos_personal',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('id_persona', sa.String(length=10), nullable=False),
    sa.Column('tipo_sustituto', sa.Enum('DIRECTO', 'SOLIDADRIDAD', name='tipoSustituto'), nullable=False),
    sa.Column('apellidos', sa.String(length=80), nullable=False),
    sa.Column('nombres', sa.String(length=80), nullable=False),
    sa.Column('numero_carnet', sa.String(length=15), nullable=False),
    sa.Column('desde', sa.Date(), nullable=False),
    sa.Column('hasta', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['datos_personales.identificacion'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sustitutos_personal_id'), 'sustitutos_personal', ['id'], unique=False)
    tipoLicenciaConduccion = postgresql.ENUM(TipoLicenciaConduccion, name="tipoLicenciaConduccion")
    tipoLicenciaConduccion.create(op.get_bind(), checkfirst=True)
    op.add_column('datos_personales', sa.Column('tipo_licencia_conduccion',tipoLicenciaConduccion, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datos_personales', 'tipo_licencia_conduccion')
    op.drop_index(op.f('ix_sustitutos_personal_id'), table_name='sustitutos_personal')
    op.drop_table('sustitutos_personal')
    op.drop_index(op.f('ix_regimen_disciplinario_id'), table_name='regimen_disciplinario')
    op.drop_table('regimen_disciplinario')
    op.drop_index(op.f('ix_informacion_bancaria_personal_id'), table_name='informacion_bancaria_personal')
    op.drop_table('informacion_bancaria_personal')
    op.drop_index(op.f('ix_contactos_emergencia_personal_id'), table_name='contactos_emergencia_personal')
    op.drop_table('contactos_emergencia_personal')
    op.drop_index(op.f('ix_tipos_nombramientos_id'), table_name='tipos_nombramientos')
    op.drop_table('tipos_nombramientos')
    op.drop_index(op.f('ix_tipos_contratos_id'), table_name='tipos_contratos')
    op.drop_table('tipos_contratos')
    op.drop_index(op.f('ix_sanciones_id'), table_name='sanciones')
    op.drop_table('sanciones')
    op.drop_table('regimenes_laborales')
    op.drop_index(op.f('ix_motivos_desvinculacion_id'), table_name='motivos_desvinculacion')
    op.drop_table('motivos_desvinculacion')
    op.drop_index(op.f('ix_modalidades_contractuales_id'), table_name='modalidades_contractuales')
    op.drop_table('modalidades_contractuales')
    op.drop_index(op.f('ix_estados_sumarios_id'), table_name='estados_sumarios')
    op.drop_table('estados_sumarios')
    sa.Enum(name="tipoCuenta").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="mes").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="tipoFalta").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="tipoSustituto").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="tipoLicenciaConduccion").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
