"""cambios en modelo experiencia laboral

Revision ID: 65b516548578
Revises: 13f1892aebb7
Create Date: 2021-11-28 18:17:18.775741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b516548578'
down_revision = '13f1892aebb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiencia_laboral_personal', sa.Column('unidad_administrativa', sa.String(length=120), nullable=False))
    op.add_column('experiencia_laboral_personal', sa.Column('motivo_ingreso', sa.String(length=120), nullable=False))
    op.add_column('experiencia_laboral_personal', sa.Column('motivo_salida', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiencia_laboral_personal', 'motivo_salida')
    op.drop_column('experiencia_laboral_personal', 'motivo_ingreso')
    op.drop_column('experiencia_laboral_personal', 'unidad_administrativa')
    # ### end Alembic commands ###
