"""tabla ies_nacionales

Revision ID: 6cf89f8285ea
Revises: 4ddffce21037
Create Date: 2021-10-20 19:34:44.548595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6cf89f8285ea'
down_revision = '4ddffce21037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ies_nacionales',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('codigo', sa.String(length=4), nullable=False),
    sa.Column('institucion', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ies_nacionales_id'), 'ies_nacionales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ies_nacionales_id'), table_name='ies_nacionales')
    op.drop_table('ies_nacionales')
    # ### end Alembic commands ###
