"""nueva columna en tabla datos_personales

Revision ID: 6e795c658b58
Revises: 6f4de2320d9d
Create Date: 2021-12-09 13:46:32.204226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e795c658b58'
down_revision = '6f4de2320d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datos_personales', sa.Column('sustituto', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datos_personales', 'sustituto')
    # ### end Alembic commands ###
