"""cargar nacionalidades

Revision ID: 8098b2c87c7f
Revises: dff6a42542b2
Create Date: 2021-09-29 15:41:18.024726

"""
from typing import List
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session
from sqlalchemy.sql.expression import delete, select
from app.models.core.modelos_principales import  Nacionalidad


# revision identifiers, used by Alembic.
revision = '8098b2c87c7f'
down_revision = 'dff6a42542b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    nacionalidades =[   
        'TSACHILA',
        'WOARANI',
        'ZARAPA',
        'ANDOA',
        'KICHWA',
        'PASTOS',
        'NATABUELA',
        'OTAVALO',
        'KARANKI',
        'KAYAMBI',
        'KITUKARA',
        'PANZALEO',
        'CHIBUELO',
        'SALASAKA',
        'KAÑARI',
        'SARAGURU',
        'PALTAS',
        'MANTA',
        'HUANCAVILCA',
        'ACHUAR',
        'AWA',
        'AL COFAN',
        'CHACHI',
        'EPERA',
        'HUAORANI',
        'SECOYA',
        'SHUAR',
        'SIONA',
        'NO APLICA'
    ]
    session = Session(bind=op.get_bind())
    lista: List[Nacionalidad] = []
    for nacionalidad in nacionalidades:
        
        results = session.execute(
            select(Nacionalidad).where(nacionalidad==nacionalidad)
        )
        existe = results.all()
        if existe:
            break
        lista.append(Nacionalidad(nacionalidad=nacionalidad))
        
    
    print(lista)
    session.add_all(lista)
    session.commit()
        
    session.close()

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())
    session.execute(delete(Nacionalidad))
    session.commit()
    session.close()
    
    # ### end Alembic commands ###
