"""cambios en DetalleExpedienteLaboral

Revision ID: 8832874f27c2
Revises: 64590e4a0e91
Create Date: 2021-10-08 13:51:58.435588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8832874f27c2'
down_revision = '64590e4a0e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalles_expedientes_laborales', 'id_tipo_documento',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('detalles_expedientes_laborales', 'puesto_jerarquico',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.execute('ALTER TABLE detalles_expedientes_laborales ALTER COLUMN remuneracion_mensual TYPE decimal(7,2)')
    op.execute('ALTER TABLE detalles_expedientes_laborales ALTER COLUMN remuneracion_hora TYPE decimal(6,2)')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalles_expedientes_laborales', 'puesto_jerarquico',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('detalles_expedientes_laborales', 'id_tipo_documento',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.execute('ALTER TABLE detalles_expedientes_laborales ALTER COLUMN remuneracion_mensual TYPE decimal(4,2)')
    op.execute('ALTER TABLE detalles_expedientes_laborales ALTER COLUMN remuneracion_hora TYPE decimal(4,2)')
    # ### end Alembic commands ###
