"""actualizacion app/models/dath/modelos.py

Revision ID: 88c3e50e8cc6
Revises: 58c1e914b39a
Create Date: 2021-11-24 15:20:16.344656

"""
from alembic import op
from pydantic.main import create_model
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88c3e50e8cc6'
down_revision = '58c1e914b39a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('declaraciones_patrimoniales',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('id_persona', sa.String(length=10), nullable=False),
    sa.Column('tipo_declaracion', sa.Enum('inicio', 'periodica', 'fin', name='tipoDeclaracion'), nullable=False),
    sa.Column('fecha_presentación', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['datos_personales.identificacion'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declaraciones_patrimoniales_id'), 'declaraciones_patrimoniales', ['id'], unique=False)
    op.create_table('familiares_personal',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('id_persona', sa.String(length=10), nullable=False),
    sa.Column('parentesco', sa.String(length=30), nullable=False),
    sa.Column('identificacion', sa.String(length=10), nullable=False),
    sa.Column('nombres', sa.String(length=60), nullable=False),
    sa.Column('apellidos', sa.String(length=60), nullable=False),
    sa.Column('sexo', postgresql('HOMBRE', 'MUJER', name='sexo', create_type=False), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['datos_personales.identificacion'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_familiares_personal_id'), 'familiares_personal', ['id'], unique=False)
    op.add_column('detalles_expedientes_laborales', sa.Column('id_tipo_contrato', postgresql.UUID(), nullable=True))
    op.add_column('detalles_expedientes_laborales', sa.Column('id_tipo_nombramiento', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'detalles_expedientes_laborales', 'tipos_contratos', ['id_tipo_contrato'], ['id'])
    op.create_foreign_key(None, 'detalles_expedientes_laborales', 'tipos_contratos', ['id_tipo_nombramiento'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detalles_expedientes_laborales', type_='foreignkey')
    op.drop_constraint(None, 'detalles_expedientes_laborales', type_='foreignkey')
    op.drop_column('detalles_expedientes_laborales', 'id_tipo_nombramiento')
    op.drop_column('detalles_expedientes_laborales', 'id_tipo_contrato')
    op.drop_index(op.f('ix_familiares_personal_id'), table_name='familiares_personal')
    op.drop_table('familiares_personal')
    op.drop_index(op.f('ix_declaraciones_patrimoniales_id'), table_name='declaraciones_patrimoniales')
    op.drop_table('declaraciones_patrimoniales')
    sa.Enum(name='tipoDeclaracion').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
