"""cargar tipos docentes

Revision ID: 8a9b4bb6886e
Revises: 54fa755c3288
Create Date: 2021-10-05 22:19:40.155888

"""
from alembic import op
import sqlalchemy as sa
from typing import List
from sqlalchemy.orm.session import Session
from app.models.core.modelos_principales import TipoDocenteLOES
from sqlalchemy.sql.expression import delete, select

# revision identifiers, used by Alembic.
revision = '8a9b4bb6886e'
down_revision = '54fa755c3288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tipos = [
        'TECNICO DOCENTE',
        'TECNICO LABORATORIO',
        'TECNICO INVESTIGACION',
        'TECNICO ARTES'
    ]

    session = Session(bind=op.get_bind())
    lista: List[TipoDocenteLOES] = []
    for tipo in tipos:
        
        results = session.execute(
            select(TipoDocenteLOES).where(TipoDocenteLOES.tipo_docente==tipo)
        )
        existe = results.all()
        if existe:
            break
        lista.append(TipoDocenteLOES(tipo_docente=tipo))
        

    session.add_all(lista)
    session.commit()
        
    session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())
    session.execute(delete(TipoDocenteLOES))
    session.commit()
    session.close()
    # ### end Alembic commands ###
