"""cambio foreing key en campo_educativo_detallado

Revision ID: 9c87666b10bc
Revises: 68b435498e74
Create Date: 2021-10-28 11:11:09.401914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c87666b10bc'
down_revision = '68b435498e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formacion_academica_personal', sa.Column('id_campo_especifico', postgresql.UUID(), nullable=False))
    op.drop_constraint('formacion_academica_personal_id_campo_detallado_fkey', 'formacion_academica_personal', type_='foreignkey')
    op.create_foreign_key('formacion_academica_personal_id_campo_educativo_especifico_fk', 'formacion_academica_personal', 'campo_educativo_especifico', ['id_campo_especifico'], ['id'])
    op.drop_column('formacion_academica_personal', 'id_campo_detallado')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formacion_academica_personal', sa.Column('id_campo_detallado', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('formacion_academica_personal_id_campo_educativo_especifico_fk', 'formacion_academica_personal', type_='foreignkey')
    op.create_foreign_key('formacion_academica_personal_id_campo_detallado_fkey', 'formacion_academica_personal', 'campo_educativo_detallado', ['id_campo_detallado'], ['id'])
    op.drop_column('formacion_academica_personal', 'id_campo_especifico')
    # ### end Alembic commands ###
