"""cambios en modelo capacitación 29/11/2021 14:34

Revision ID: abec984c3c0f
Revises: dbb75bfc23c1
Create Date: 2021-11-29 14:34:43.981378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abec984c3c0f'
down_revision = 'dbb75bfc23c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capacitaciones', sa.Column(
        'certificado', sa.String(length=120), nullable=True))
    session = Session(bind=op.get_bind())
    op.alter_column('capacitaciones', 'tipo_certificado', type_ = sa.Enum("ASISTENCIA", "APROBACIÓN", "PARTICIPACIÓN",name="tipoCertificado", nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capacitaciones', 'certificado')
    op.alter_column('capacitaciones', 'tipo_certificado', type_ = sa.Enum("ASISTENCIA", "APROBACION",name="tipoCertificado", nullable=False))
    
    # ### end Alembic commands ###
