"""modelos EstadoCivil, EstructuraInstitucional  y renombrar tabla en Modelo TipoEscalafonNombramiento

Revision ID: abf53ee9a86f
Revises: b5e2f22ef278
Create Date: 2021-09-09 10:46:10.954104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abf53ee9a86f'
down_revision = 'b5e2f22ef278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_civiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado_civil', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estructura_organica_institucional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('id_area', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_escalafones_nombramientos',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('escalafon_nombramiento', sa.String(length=50), nullable=False),
    sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escalafon_nombramiento')
    )
    op.create_index(op.f('ix_tipos_escalafones_nombramientos_id'), 'tipos_escalafones_nombramientos', ['id'], unique=False)
    op.drop_index('ix_tipos_relaciones_nombramientos_id', table_name='tipos_relaciones_nombramientos')
    op.drop_table('tipos_relaciones_nombramientos')
    op.create_unique_constraint('uc_email', 'cuentas_usuarios', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_email', 'cuentas_usuarios', type_='unique')
    op.create_table('tipos_relaciones_nombramientos',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('escalafon_nombramiento', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tipos_relaciones_nombramientos_pkey'),
    sa.UniqueConstraint('escalafon_nombramiento', name='tipos_relaciones_nombramientos_escalafon_nombramiento_key')
    )
    op.create_index('ix_tipos_relaciones_nombramientos_id', 'tipos_relaciones_nombramientos', ['id'], unique=False)
    op.drop_index(op.f('ix_tipos_escalafones_nombramientos_id'), table_name='tipos_escalafones_nombramientos')
    op.drop_table('tipos_escalafones_nombramientos')
    op.drop_table('estructura_organica_institucional')
    op.drop_table('estados_civiles')
    # ### end Alembic commands ###
