"""cargar areas institucionales

Revision ID: af0f4d8a44a3
Revises: 8098b2c87c7f
Create Date: 2021-10-04 16:36:01.917704

"""
from typing import List
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session
import json

from app.models.core.modelos_principales import AreaInstitucion

# revision identifiers, used by Alembic.
revision = 'af0f4d8a44a3'
down_revision = '8098b2c87c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session =  Session(bind=op.get_bind())
    listadoAreas: List[AreaInstitucion] = []
    try:
        file_path = ".\\app\\utils\\areas.json"
        with open(file_path, encoding='utf8') as f:
            areas = json.load(f)
        for area in areas:
            a = AreaInstitucion()
            a.nombre = area['nombre']
            a.codigo = area['codigo']
            listadoAreas.append(a)
        session.add_all(listadoAreas)
        session.commit()
    except Exception as ex:
        print(f'{ex}')
    finally:
        session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    session  = Session(bind=op.get_bind())
    session.execute('delete from areas_institucionales')
    session.commit()
    session.execute('ALTER SEQUENCE areas_institucionales_id_seq RESTART WITH 1')
    session.commit()
    session.close()
    # ### end Alembic commands ###
