"""Crear usuario Administrador

Revision ID: b5e2f22ef278
Revises: e7aa6d10574a
Create Date: 2021-08-18 14:12:20.994952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import select, delete
from app.models.auth.cuentas_usuarios import Rol, CuentaUsuario
from sqlalchemy.orm.session import Session
from decouple import config 
import bcrypt
# revision identifiers, used by Alembic.
revision = 'b5e2f22ef278'
down_revision = 'e7aa6d10574a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('cuentas_usuarios') as bop:
        bop.alter_column('segundo_segundo', new_column_name='segundo_apellido')

    session = Session(bind=op.get_bind())
    rol = Rol(rol="Administrador", descripcion="Este rol permite la gestionar los la aplicación y los usuarios de la misma")
    session.add(rol)
    session.commit()
    (r,) = session.execute(select(Rol).where(Rol.rol=="Administrador"))
    print(r[0])

    usuario = CuentaUsuario()
    usuario.email = config("ADMIN_EMAIL")
    usuario.primer_nombre = config("ADMIN_NAME1")
    usuario.segundo_nombre = config("ADMIN_NAME2")
    usuario.primer_apellido = config("ADMIN_LASTNAME1")
    usuario.segundo_apellido = config("ADMIN_LASTNAME2")
    usuario.clave_encriptada = CuentaUsuario.cifrar_clave(config('ADMIN_PASS'))
    
    usuario.roles = [r[0]]
    session.add(usuario)
    print(usuario.__dict__)
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    session = Session(bind=op.get_bind())

    session.execute("truncate table roles_usuarios")
    session.execute("truncate table tokens_autorizaciones")
    session.execute(delete(CuentaUsuario).where(CuentaUsuario.email==config("ADMIN_EMAIL")))

    session.execute(delete(Rol).where(Rol.rol=="Administrador"))

    session.commit()

    with op.batch_alter_table('cuentas_usuarios') as bop:
        bop.alter_column('segundo_apellido', new_column_name='segundo_segundo')
    # ### end Alembic commands ###
