"""cargar nivel educativo

Revision ID: bbfd8b9b5235
Revises: e09335b501ee
Create Date: 2021-10-05 22:04:04.257276

"""
from alembic import op
import sqlalchemy as sa
from typing import List
from sqlalchemy.orm.session import Session
from sqlalchemy.sql.expression import delete, select
from app.models.core.modelos_principales import NivelEducativo


# revision identifiers, used by Alembic.
revision = 'bbfd8b9b5235'
down_revision = 'e09335b501ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    niveles = [
        'TERCER NIVEL',
        'CUARTO NIVEL',
        'TERCER/ CUARTO NIVEL'
    ]
    session = Session(bind=op.get_bind())
    lista: List[NivelEducativo] = []
    for nivel in niveles:
        
        results = session.execute(
            select(NivelEducativo).where(NivelEducativo.nivel==nivel)
        )
        existe = results.all()
        if existe:
            break
        lista.append(NivelEducativo(nivel=nivel))
        
    
   
    session.add_all(lista)
    session.commit()
        
    session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())
    session.execute(delete(NivelEducativo))
    session.commit()
    session.close()
    # ### end Alembic commands ###
