"""columna descripcion en  DetalleExpedienteLboral

Revision ID: c14126191d04
Revises: 8832874f27c2
Create Date: 2021-10-19 10:37:35.546304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14126191d04'
down_revision = '8832874f27c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalles_expedientes_laborales', sa.Column('descripcion', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detalles_expedientes_laborales', 'descripcion')
    # ### end Alembic commands ###
