"""cambios en resgistrado_en

Revision ID: c6841781b9f8
Revises: 471d53bfb20c
Create Date: 2021-08-04 11:49:36.926504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6841781b9f8'
down_revision = '471d53bfb20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('registrado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('roles', sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'actualizado_en')
    op.drop_column('roles', 'registrado_en')
    # ### end Alembic commands ###
