"""cargar datos en tabla  tipo_beca

Revision ID: d352d6001091
Revises: 1c8e0ddd7258
Create Date: 2021-10-20 09:31:09.535717

"""
from typing import List
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import session
from sqlalchemy.sql.expression import select, delete
from app.models.core.modelos_principales import TipoBeca
from sqlalchemy.orm.session import Session


# revision identifiers, used by Alembic.
revision = 'd352d6001091'
down_revision = '1c8e0ddd7258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tipos = [
        'TOTAL',
        'PARCIAL'
    ]
    session = Session(bind=op.get_bind())
    lista:List[TipoBeca] = []
    
    for tipo in tipos:
        results = session.execute(
            select(TipoBeca).where(
                TipoBeca.tipo_beca == tipo
            )
        )
        existe = results.all()
        if existe:
            break
        lista.append(TipoBeca(tipo_beca=tipo))
    
    session.add_all(lista)
    session.commit()
    session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())
    session.execute(delete(TipoBeca))
    session.commit()
    session.close()
    # ### end Alembic commands ###
