"""tabla provincias y cantones y carga de datos

Revision ID: da51b9dfff5f
Revises: 51e67ffe7260
Create Date: 2021-07-28 15:52:18.033568

"""
from alembic import op
import sqlalchemy as sa
import json

from sqlalchemy.orm.session import Session
from app.models.core.modelos_principales import Provincia, Canton
# revision identifiers, used by Alembic.
revision = 'da51b9dfff5f'
down_revision = '51e67ffe7260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provincias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provincias_id'), 'provincias', ['id'], unique=False)
    op.create_table('cantones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canton', sa.String(length=120), nullable=True),
    sa.Column('provincia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    ### Insert data
    
    session = Session(bind=op.get_bind())
    print("Insertando datos ...")
    try:
        file_path = '.\\app\\utils\\provincias_cantones.json'
        with open(file_path) as f:
            listado_provincias = json.load(f)
        for fila in listado_provincias:
            cantones = []
            p = Provincia()
            p.provincia= fila["provincia"]
            for canton in fila["cantones"]:
                c = Canton()
                c.canton = canton
                cantones.append(c)
            p.cantones = cantones
            session.add(p)
        session.commit()

        print("Datos insertados")
    except Exception as ex:

        print(f"{ex}")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cantones')
    op.drop_index(op.f('ix_provincias_id'), table_name='provincias')
    op.drop_table('provincias')
    # ### end Alembic commands ###
