"""cambios en modelo capacitación adición de clave foranea y nueva columna

Revision ID: dbb75bfc23c1
Revises: 65b516548578
Create Date: 2021-11-29 10:39:43.790510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dbb75bfc23c1'
down_revision = '65b516548578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capacitaciones', sa.Column('id_tipo_evento', postgresql.UUID(), nullable=False))
    op.add_column('capacitaciones', sa.Column('nombre', sa.String(length=30), nullable=False))
    op.create_foreign_key('capacitaciones_id_tipo_evento_fk', 'capacitaciones', 'tipos_eventos', ['id_tipo_evento'], ['id'])
    op.drop_column('capacitaciones', 'tipo_evento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capacitaciones', sa.Column('tipo_evento', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint('capacitaciones_id_tipo_evento_fk', 'capacitaciones', type_='foreignkey')
    op.drop_column('capacitaciones', 'nombre')
    op.drop_column('capacitaciones', 'id_tipo_evento')
    # ### end Alembic commands ###
