"""cargar tiempo dedicación

Revision ID: e09335b501ee
Revises: 1f83b3b1d98e
Create Date: 2021-10-05 21:57:57.465974

"""
from typing import List
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session
from sqlalchemy.sql.expression import delete, select
from app.models.core.modelos_principales import TiempoDedicacionProfesor


# revision identifiers, used by Alembic.
revision = 'e09335b501ee'
down_revision = '1f83b3b1d98e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    dediacaiones = [
        'EXCLUSIVA O TIEMPO COMPLETO',
        'SEMI EXCLUSIVA O MEDIO TIEMPO',
        'TIEMPO PARCIAL'
    ]

    session = Session(bind=op.get_bind())
    lista: List[TiempoDedicacionProfesor] = []
    for dedicacion in dediacaiones:
        
        results = session.execute(
            select(TiempoDedicacionProfesor).where(TiempoDedicacionProfesor.tiempo_dedicacion==dedicacion)
        )
        existe = results.all()
        if existe:
            break
        lista.append(TiempoDedicacionProfesor(tiempo_dedicacion=dedicacion))
        
    
    
    session.add_all(lista)
    session.commit()
        
    session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())
    session.execute(delete(TiempoDedicacionProfesor))
    session.commit()
    session.close()
    # ### end Alembic commands ###
