"""cambios en cantones, paises y provincias

Revision ID: e7aa6d10574a
Revises: baec5138cbbd
Create Date: 2021-08-10 12:33:38.474329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7aa6d10574a'
down_revision = 'baec5138cbbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_canton_provincia', 'cantones', ['canton', 'provincia_id'])
    op.alter_column('categorias_docentes_losep', 'categoria_docente',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('discapacidades', 'discapacidad',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.create_unique_constraint('uc_pais', 'paises', ['pais'])
    op.create_unique_constraint('uc_provincia', 'provincias', ['provincia'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_provincia', 'provincias', type_='unique')
    op.drop_constraint('uc_pais', 'paises', type_='unique')
    op.alter_column('discapacidades', 'discapacidad',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('categorias_docentes_losep', 'categoria_docente',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('uc_canton_provincia', 'cantones', type_='unique')
    # ### end Alembic commands ###
