"""creacion tablas campo_educativo_amplio, campo_educativo_especifico y campo_educativo_detallado

Revision ID: e86feeb8c8f7
Revises: 4541e6adbb9c
Create Date: 2021-10-20 10:55:53.044575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e86feeb8c8f7'
down_revision = '4541e6adbb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campo_educativo_amplio',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('codigo', sa.String(length=8), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campo_educativo_amplio_id'), 'campo_educativo_amplio', ['id'], unique=False)
    op.create_table('campo_educativo_especifico',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('id_campo_amplio', postgresql.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=8), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['id_campo_amplio'], ['campo_educativo_amplio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campo_educativo_especifico_id'), 'campo_educativo_especifico', ['id'], unique=False)
    op.create_table('campo_educativo_detallado',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('id_campo_especifico', postgresql.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=8), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['id_campo_especifico'], ['campo_educativo_especifico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campo_educativo_detallado_id'), 'campo_educativo_detallado', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campo_educativo_detallado_id'), table_name='campo_educativo_detallado')
    op.drop_table('campo_educativo_detallado')
    op.drop_index(op.f('ix_campo_educativo_especifico_id'), table_name='campo_educativo_especifico')
    op.drop_table('campo_educativo_especifico')
    op.drop_index(op.f('ix_campo_educativo_amplio_id'), table_name='campo_educativo_amplio')
    op.drop_table('campo_educativo_amplio')
    # ### end Alembic commands ###
