"""actualizacion app/models/dath/modelos.py correccion

Revision ID: edf24944fc17
Revises: 88c3e50e8cc6
Create Date: 2021-11-24 15:53:10.814228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf24944fc17'
down_revision = '88c3e50e8cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('detalles_expedientes_laborales_id_tipo_nombramiento_fkey', 'detalles_expedientes_laborales', type_='foreignkey')
    op.create_foreign_key(None, 'detalles_expedientes_laborales', 'tipos_nombramientos', ['id_tipo_nombramiento'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detalles_expedientes_laborales', type_='foreignkey')
    op.create_foreign_key('detalles_expedientes_laborales_id_tipo_nombramiento_fkey', 'detalles_expedientes_laborales', 'tipos_contratos', ['id_tipo_nombramiento'], ['id'])
    # ### end Alembic commands ###
