"""añadir columna numero_declaracion en tabla declaraciones_patrimoniales

Revision ID: f1b81398bf83
Revises: 26d5745ee8ec
Create Date: 2021-12-07 10:01:49.814306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b81398bf83'
down_revision = '26d5745ee8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('declaraciones_patrimoniales', sa.Column('numero_declaracion', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('declaraciones_patrimoniales', 'numero_declaracion')
    # ### end Alembic commands ###
