"""cargar estados civiles

Revision ID: f4229626f4f2
Revises: 9d83e8d026dc
Create Date: 2022-03-16 18:19:28.249872

"""
from alembic import op
import sqlalchemy as sa
from typing import List
from sqlalchemy.orm.session import Session
from app.models.core.modelos_principales import EstadoCivil
from sqlalchemy.sql.expression import delete, select


# revision identifiers, used by Alembic.
revision = 'f4229626f4f2'
down_revision = '9d83e8d026dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    estados_civiles: List[str] = ['SOLTERO/A', 'CASADO/A', 'DIVORCIADO/A', 'VIUDO/A']

    session = Session(bind=op.get_bind())
    lista: List[EstadoCivil] = []
    for estado_civil in estados_civiles:
        
        results = session.execute(
            select(EstadoCivil).where(EstadoCivil.estado_civil==estado_civil)
        )
        existe = results.all()
        if existe:
            break
        lista.append(EstadoCivil(estado_civil=estado_civil))
        

    session.add_all(lista)
    session.commit()
        
    session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())
    session.execute(delete(EstadoCivil))
    session.commit()
    session.close()
    # ### end Alembic commands ###
